import type { RecordCard } from "./types";

export const CARDS: RecordCard[] = [
  {
    symbol: "AAPL",
    name: "Apple",
    sub: "Apple Inc.",
    desc: "Hardware ecosystem, services revenue, and on-device AI support resilient cash flow.",
    tags: ["Tech", "Consumer", "AI"],
    image: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=900&q=80",
    tint: "#7dd3fc",
    change: "+1.8%",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    sub: "Microsoft",
    desc: "Azure and Copilot commercialization continue to anchor cloud-driven valuation.",
    tags: ["Cloud", "SaaS", "AI"],
    image: "https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=900&q=80",
    tint: "#60a5fa",
    change: "+2.1%",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    sub: "NVIDIA",
    desc: "Data-center GPU demand remains elevated as AI capital spending expands.",
    tags: ["Chips", "AI"],
    image: "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=900&q=80",
    tint: "#4ade80",
    change: "+3.4%",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    sub: "Alphabet",
    desc: "Search ads stay durable while Gemini and cloud add new growth optionality.",
    tags: ["Ads", "Cloud", "AI"],
    image: "https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=900&q=80",
    tint: "#facc15",
    change: "+0.9%",
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    sub: "Amazon",
    desc: "Retail efficiency and AWS recovery continue to lift margin expectations.",
    tags: ["Commerce", "Cloud"],
    image: "https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=900&q=80",
    tint: "#f59e0b",
    change: "+1.2%",
  },
  {
    symbol: "TSLA",
    name: "Tesla",
    sub: "Tesla",
    desc: "EV demand, energy storage, and autonomy narratives drive valuation swings.",
    tags: ["Auto", "Energy", "AI"],
    image: "https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&q=80",
    tint: "#fb7185",
    change: "-0.6%",
  },
  {
    symbol: "META",
    name: "Meta",
    sub: "Meta Platforms",
    desc: "Advertising cash flow remains strong as AI ranking improves platform efficiency.",
    tags: ["Ads", "Social", "AI"],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=900&q=80",
    tint: "#a78bfa",
    change: "+2.6%",
  },
  {
    symbol: "JPM",
    name: "JPMorgan",
    sub: "JPMorgan Chase",
    desc: "Balance-sheet quality and deposit scale keep it ahead of banking peers.",
    tags: ["Finance", "Banking"],
    image: "https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=900&q=80",
    tint: "#38bdf8",
    change: "+0.4%",
  },
  {
    symbol: "V",
    name: "Visa",
    sub: "Visa Inc.",
    desc: "Global payment network effects and cross-border recovery support revenue elasticity.",
    tags: ["Payments", "Consumer"],
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=900&q=80",
    tint: "#818cf8",
    change: "+0.7%",
  },
  {
    symbol: "AVGO",
    name: "Broadcom",
    sub: "Broadcom",
    desc: "Custom AI silicon demand and VMware integration increase software mix.",
    tags: ["Chips", "Software"],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900&q=80",
    tint: "#f472b6",
    change: "+1.9%",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth",
    sub: "UnitedHealth",
    desc: "Insurance, pharmacy benefits, and care services provide defensive stability.",
    tags: ["Healthcare", "Insurance"],
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=900&q=80",
    tint: "#2dd4bf",
    change: "-0.3%",
  },
  {
    symbol: "BRK.B",
    name: "Berkshire",
    sub: "Berkshire Hathaway",
    desc: "Insurance float, energy, rail, and equity holdings form a long-term value base.",
    tags: ["Value", "Insurance"],
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=900&q=80",
    tint: "#fbbf24",
    change: "+0.5%",
  },
];
